---
driver:
  name: vagrant
  customize:
    memory: 4096

provisioner:
  name: chef_solo

transport:
  ssh_key:  'C:\\Users\\Iman Kurniawan\\.vagrant.d\\insecure_private_key'

platforms:
  - name: centos-7.1

suites:
  - name: default
    run_list:
      - recipe[nagioslogserver::default]
    attributes:
